// Minimal type stubs for Cloudflare Workers virtual modules.
// These are provided at runtime by the workerd / @cloudflare/vite-plugin runtime.
// A full typed Env interface will be generated by `wrangler types` in the
// accounts-data-layer slice. Until then, bindings are accessed via `as any`.
declare module 'cloudflare:workers' {
  /** The current Worker's environment bindings (D1, KV, R2, secrets, …). */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const env: Record<string, any>
}
