// Extends the Cloudflare Workers Env interface with OAuth secrets and other
// Worker secrets that are NOT in wrangler.jsonc (secrets must never be committed).
// worker-configuration.d.ts (project root, generated by `wrangler types`) declares
// interface Env and Cloudflare.Env with bindings (DB: D1Database, OPENROUTER_API_KEY).
// This file extends BOTH via TypeScript declaration merging so that
// `import { env } from 'cloudflare:workers'` is fully typed throughout the codebase.
// The `cloudflare:workers` module uses `export = CloudflareWorkersModule` where
// `env` is typed as `Cloudflare.Env`, so we extend the Cloudflare namespace.

// Extend Cloudflare.Env (flows into `env` from `cloudflare:workers`).
declare namespace Cloudflare {
  interface Env {
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_BASE_URL: string | undefined;
    BETTER_AUTH_API_KEY: string | undefined;
    OPENROUTER_API_KEY: string;
  }
}

// Keep global Env in sync (used directly in lib/auth.ts, server/journeys.ts, etc.).
interface Env {
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_BASE_URL: string | undefined;
  BETTER_AUTH_API_KEY: string | undefined;
  OPENROUTER_API_KEY: string;
}
