/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiDemoStreamRouteImport } from './routes/api/demo-stream'
import { Route as AuthenticatedSampleRouteImport } from './routes/_authenticated/sample'
import { Route as AuthenticatedQuotaFixtureRouteImport } from './routes/_authenticated/quota-fixture'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSampleIndexRouteImport } from './routes/_authenticated/sample/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSampleQuizRouteImport } from './routes/_authenticated/sample/quiz'
import { Route as AuthenticatedSampleLesson2RouteImport } from './routes/_authenticated/sample/lesson-2'
import { Route as AuthenticatedSampleLesson1RouteImport } from './routes/_authenticated/sample/lesson-1'
import { Route as AuthenticatedLessonFixtureRouteImport } from './routes/_authenticated/lesson/fixture'
import { Route as AuthenticatedJourneyNewRouteImport } from './routes/_authenticated/journey/new'
import { Route as AuthenticatedJourneyJourneyIdRouteImport } from './routes/_authenticated/journey/$journeyId'
import { Route as ApiJourneyJourneyIdLessonRouteImport } from './routes/api/journey/$journeyId/lesson'
import { Route as AuthenticatedJourneyJourneyIdProgressRouteImport } from './routes/_authenticated/journey/$journeyId/progress'
import { Route as AuthenticatedJourneyJourneyIdInterviewRouteImport } from './routes/_authenticated/journey/$journeyId/interview'
import { Route as AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteImport } from './routes/_authenticated/journey/$journeyId/waypoint/$waypointId'
import { Route as AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRouteImport } from './routes/_authenticated/journey/$journeyId/waypoint/$waypointId/index'
import { Route as AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRouteImport } from './routes/_authenticated/journey/$journeyId/waypoint/$waypointId/quiz'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDemoStreamRoute = ApiDemoStreamRouteImport.update({
  id: '/api/demo-stream',
  path: '/api/demo-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSampleRoute = AuthenticatedSampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotaFixtureRoute =
  AuthenticatedQuotaFixtureRouteImport.update({
    id: '/quota-fixture',
    path: '/quota-fixture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSampleIndexRoute =
  AuthenticatedSampleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSampleQuizRoute = AuthenticatedSampleQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedSampleRoute,
} as any)
const AuthenticatedSampleLesson2Route =
  AuthenticatedSampleLesson2RouteImport.update({
    id: '/lesson-2',
    path: '/lesson-2',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const AuthenticatedSampleLesson1Route =
  AuthenticatedSampleLesson1RouteImport.update({
    id: '/lesson-1',
    path: '/lesson-1',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const AuthenticatedLessonFixtureRoute =
  AuthenticatedLessonFixtureRouteImport.update({
    id: '/lesson/fixture',
    path: '/lesson/fixture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJourneyNewRoute = AuthenticatedJourneyNewRouteImport.update({
  id: '/journey/new',
  path: '/journey/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJourneyJourneyIdRoute =
  AuthenticatedJourneyJourneyIdRouteImport.update({
    id: '/journey/$journeyId',
    path: '/journey/$journeyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiJourneyJourneyIdLessonRoute =
  ApiJourneyJourneyIdLessonRouteImport.update({
    id: '/api/journey/$journeyId/lesson',
    path: '/api/journey/$journeyId/lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedJourneyJourneyIdProgressRoute =
  AuthenticatedJourneyJourneyIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedJourneyJourneyIdRoute,
  } as any)
const AuthenticatedJourneyJourneyIdInterviewRoute =
  AuthenticatedJourneyJourneyIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedJourneyJourneyIdRoute,
  } as any)
const AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute =
  AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteImport.update({
    id: '/waypoint/$waypointId',
    path: '/waypoint/$waypointId',
    getParentRoute: () => AuthenticatedJourneyJourneyIdRoute,
  } as any)
const AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute =
  AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute,
  } as any)
const AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute =
  AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/sample': typeof AuthenticatedSampleRouteWithChildren
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/journey/$journeyId': typeof AuthenticatedJourneyJourneyIdRouteWithChildren
  '/journey/new': typeof AuthenticatedJourneyNewRoute
  '/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sample/': typeof AuthenticatedSampleIndexRoute
  '/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
  '/journey/$journeyId/progress': typeof AuthenticatedJourneyJourneyIdProgressRoute
  '/api/journey/$journeyId/lesson': typeof ApiJourneyJourneyIdLessonRoute
  '/journey/$journeyId/waypoint/$waypointId': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteWithChildren
  '/journey/$journeyId/waypoint/$waypointId/quiz': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute
  '/journey/$journeyId/waypoint/$waypointId/': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/': typeof AuthenticatedIndexRoute
  '/journey/$journeyId': typeof AuthenticatedJourneyJourneyIdRouteWithChildren
  '/journey/new': typeof AuthenticatedJourneyNewRoute
  '/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sample': typeof AuthenticatedSampleIndexRoute
  '/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
  '/journey/$journeyId/progress': typeof AuthenticatedJourneyJourneyIdProgressRoute
  '/api/journey/$journeyId/lesson': typeof ApiJourneyJourneyIdLessonRoute
  '/journey/$journeyId/waypoint/$waypointId/quiz': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute
  '/journey/$journeyId/waypoint/$waypointId': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/_authenticated/sample': typeof AuthenticatedSampleRouteWithChildren
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/journey/$journeyId': typeof AuthenticatedJourneyJourneyIdRouteWithChildren
  '/_authenticated/journey/new': typeof AuthenticatedJourneyNewRoute
  '/_authenticated/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/_authenticated/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/_authenticated/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/_authenticated/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/sample/': typeof AuthenticatedSampleIndexRoute
  '/_authenticated/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
  '/_authenticated/journey/$journeyId/progress': typeof AuthenticatedJourneyJourneyIdProgressRoute
  '/api/journey/$journeyId/lesson': typeof ApiJourneyJourneyIdLessonRoute
  '/_authenticated/journey/$journeyId/waypoint/$waypointId': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteWithChildren
  '/_authenticated/journey/$journeyId/waypoint/$waypointId/quiz': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute
  '/_authenticated/journey/$journeyId/waypoint/$waypointId/': typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/health'
    | '/sign-in'
    | '/account'
    | '/quota-fixture'
    | '/sample'
    | '/api/demo-stream'
    | '/journey/$journeyId'
    | '/journey/new'
    | '/lesson/fixture'
    | '/sample/lesson-1'
    | '/sample/lesson-2'
    | '/sample/quiz'
    | '/api/auth/$'
    | '/sample/'
    | '/journey/$journeyId/interview'
    | '/journey/$journeyId/progress'
    | '/api/journey/$journeyId/lesson'
    | '/journey/$journeyId/waypoint/$waypointId'
    | '/journey/$journeyId/waypoint/$waypointId/quiz'
    | '/journey/$journeyId/waypoint/$waypointId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/health'
    | '/sign-in'
    | '/account'
    | '/quota-fixture'
    | '/api/demo-stream'
    | '/'
    | '/journey/$journeyId'
    | '/journey/new'
    | '/lesson/fixture'
    | '/sample/lesson-1'
    | '/sample/lesson-2'
    | '/sample/quiz'
    | '/api/auth/$'
    | '/sample'
    | '/journey/$journeyId/interview'
    | '/journey/$journeyId/progress'
    | '/api/journey/$journeyId/lesson'
    | '/journey/$journeyId/waypoint/$waypointId/quiz'
    | '/journey/$journeyId/waypoint/$waypointId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/health'
    | '/sign-in'
    | '/_authenticated/account'
    | '/_authenticated/quota-fixture'
    | '/_authenticated/sample'
    | '/api/demo-stream'
    | '/_authenticated/'
    | '/_authenticated/journey/$journeyId'
    | '/_authenticated/journey/new'
    | '/_authenticated/lesson/fixture'
    | '/_authenticated/sample/lesson-1'
    | '/_authenticated/sample/lesson-2'
    | '/_authenticated/sample/quiz'
    | '/api/auth/$'
    | '/_authenticated/sample/'
    | '/_authenticated/journey/$journeyId/interview'
    | '/_authenticated/journey/$journeyId/progress'
    | '/api/journey/$journeyId/lesson'
    | '/_authenticated/journey/$journeyId/waypoint/$waypointId'
    | '/_authenticated/journey/$journeyId/waypoint/$waypointId/quiz'
    | '/_authenticated/journey/$journeyId/waypoint/$waypointId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  HealthRoute: typeof HealthRoute
  SignInRoute: typeof SignInRoute
  ApiDemoStreamRoute: typeof ApiDemoStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJourneyJourneyIdLessonRoute: typeof ApiJourneyJourneyIdLessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/demo-stream': {
      id: '/api/demo-stream'
      path: '/api/demo-stream'
      fullPath: '/api/demo-stream'
      preLoaderRoute: typeof ApiDemoStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sample': {
      id: '/_authenticated/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof AuthenticatedSampleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quota-fixture': {
      id: '/_authenticated/quota-fixture'
      path: '/quota-fixture'
      fullPath: '/quota-fixture'
      preLoaderRoute: typeof AuthenticatedQuotaFixtureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample/': {
      id: '/_authenticated/sample/'
      path: '/'
      fullPath: '/sample/'
      preLoaderRoute: typeof AuthenticatedSampleIndexRouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sample/quiz': {
      id: '/_authenticated/sample/quiz'
      path: '/quiz'
      fullPath: '/sample/quiz'
      preLoaderRoute: typeof AuthenticatedSampleQuizRouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/sample/lesson-2': {
      id: '/_authenticated/sample/lesson-2'
      path: '/lesson-2'
      fullPath: '/sample/lesson-2'
      preLoaderRoute: typeof AuthenticatedSampleLesson2RouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/sample/lesson-1': {
      id: '/_authenticated/sample/lesson-1'
      path: '/lesson-1'
      fullPath: '/sample/lesson-1'
      preLoaderRoute: typeof AuthenticatedSampleLesson1RouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/lesson/fixture': {
      id: '/_authenticated/lesson/fixture'
      path: '/lesson/fixture'
      fullPath: '/lesson/fixture'
      preLoaderRoute: typeof AuthenticatedLessonFixtureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journey/new': {
      id: '/_authenticated/journey/new'
      path: '/journey/new'
      fullPath: '/journey/new'
      preLoaderRoute: typeof AuthenticatedJourneyNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journey/$journeyId': {
      id: '/_authenticated/journey/$journeyId'
      path: '/journey/$journeyId'
      fullPath: '/journey/$journeyId'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/journey/$journeyId/lesson': {
      id: '/api/journey/$journeyId/lesson'
      path: '/api/journey/$journeyId/lesson'
      fullPath: '/api/journey/$journeyId/lesson'
      preLoaderRoute: typeof ApiJourneyJourneyIdLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/journey/$journeyId/progress': {
      id: '/_authenticated/journey/$journeyId/progress'
      path: '/progress'
      fullPath: '/journey/$journeyId/progress'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdProgressRouteImport
      parentRoute: typeof AuthenticatedJourneyJourneyIdRoute
    }
    '/_authenticated/journey/$journeyId/interview': {
      id: '/_authenticated/journey/$journeyId/interview'
      path: '/interview'
      fullPath: '/journey/$journeyId/interview'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdInterviewRouteImport
      parentRoute: typeof AuthenticatedJourneyJourneyIdRoute
    }
    '/_authenticated/journey/$journeyId/waypoint/$waypointId': {
      id: '/_authenticated/journey/$journeyId/waypoint/$waypointId'
      path: '/waypoint/$waypointId'
      fullPath: '/journey/$journeyId/waypoint/$waypointId'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteImport
      parentRoute: typeof AuthenticatedJourneyJourneyIdRoute
    }
    '/_authenticated/journey/$journeyId/waypoint/$waypointId/': {
      id: '/_authenticated/journey/$journeyId/waypoint/$waypointId/'
      path: '/'
      fullPath: '/journey/$journeyId/waypoint/$waypointId/'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRouteImport
      parentRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute
    }
    '/_authenticated/journey/$journeyId/waypoint/$waypointId/quiz': {
      id: '/_authenticated/journey/$journeyId/waypoint/$waypointId/quiz'
      path: '/quiz'
      fullPath: '/journey/$journeyId/waypoint/$waypointId/quiz'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRouteImport
      parentRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute
    }
  }
}

interface AuthenticatedSampleRouteChildren {
  AuthenticatedSampleLesson1Route: typeof AuthenticatedSampleLesson1Route
  AuthenticatedSampleLesson2Route: typeof AuthenticatedSampleLesson2Route
  AuthenticatedSampleQuizRoute: typeof AuthenticatedSampleQuizRoute
  AuthenticatedSampleIndexRoute: typeof AuthenticatedSampleIndexRoute
}

const AuthenticatedSampleRouteChildren: AuthenticatedSampleRouteChildren = {
  AuthenticatedSampleLesson1Route: AuthenticatedSampleLesson1Route,
  AuthenticatedSampleLesson2Route: AuthenticatedSampleLesson2Route,
  AuthenticatedSampleQuizRoute: AuthenticatedSampleQuizRoute,
  AuthenticatedSampleIndexRoute: AuthenticatedSampleIndexRoute,
}

const AuthenticatedSampleRouteWithChildren =
  AuthenticatedSampleRoute._addFileChildren(AuthenticatedSampleRouteChildren)

interface AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteChildren {
  AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute
  AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute
}

const AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteChildren: AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteChildren =
  {
    AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute:
      AuthenticatedJourneyJourneyIdWaypointWaypointIdQuizRoute,
    AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute:
      AuthenticatedJourneyJourneyIdWaypointWaypointIdIndexRoute,
  }

const AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteWithChildren =
  AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute._addFileChildren(
    AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteChildren,
  )

interface AuthenticatedJourneyJourneyIdRouteChildren {
  AuthenticatedJourneyJourneyIdInterviewRoute: typeof AuthenticatedJourneyJourneyIdInterviewRoute
  AuthenticatedJourneyJourneyIdProgressRoute: typeof AuthenticatedJourneyJourneyIdProgressRoute
  AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute: typeof AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteWithChildren
}

const AuthenticatedJourneyJourneyIdRouteChildren: AuthenticatedJourneyJourneyIdRouteChildren =
  {
    AuthenticatedJourneyJourneyIdInterviewRoute:
      AuthenticatedJourneyJourneyIdInterviewRoute,
    AuthenticatedJourneyJourneyIdProgressRoute:
      AuthenticatedJourneyJourneyIdProgressRoute,
    AuthenticatedJourneyJourneyIdWaypointWaypointIdRoute:
      AuthenticatedJourneyJourneyIdWaypointWaypointIdRouteWithChildren,
  }

const AuthenticatedJourneyJourneyIdRouteWithChildren =
  AuthenticatedJourneyJourneyIdRoute._addFileChildren(
    AuthenticatedJourneyJourneyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedQuotaFixtureRoute: typeof AuthenticatedQuotaFixtureRoute
  AuthenticatedSampleRoute: typeof AuthenticatedSampleRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedJourneyJourneyIdRoute: typeof AuthenticatedJourneyJourneyIdRouteWithChildren
  AuthenticatedJourneyNewRoute: typeof AuthenticatedJourneyNewRoute
  AuthenticatedLessonFixtureRoute: typeof AuthenticatedLessonFixtureRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedQuotaFixtureRoute: AuthenticatedQuotaFixtureRoute,
  AuthenticatedSampleRoute: AuthenticatedSampleRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedJourneyJourneyIdRoute:
    AuthenticatedJourneyJourneyIdRouteWithChildren,
  AuthenticatedJourneyNewRoute: AuthenticatedJourneyNewRoute,
  AuthenticatedLessonFixtureRoute: AuthenticatedLessonFixtureRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  HealthRoute: HealthRoute,
  SignInRoute: SignInRoute,
  ApiDemoStreamRoute: ApiDemoStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJourneyJourneyIdLessonRoute: ApiJourneyJourneyIdLessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
