/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiDemoStreamRouteImport } from './routes/api/demo-stream'
import { Route as AuthenticatedSampleRouteImport } from './routes/_authenticated/sample'
import { Route as AuthenticatedQuotaFixtureRouteImport } from './routes/_authenticated/quota-fixture'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSampleIndexRouteImport } from './routes/_authenticated/sample/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSampleQuizRouteImport } from './routes/_authenticated/sample/quiz'
import { Route as AuthenticatedSampleLesson2RouteImport } from './routes/_authenticated/sample/lesson-2'
import { Route as AuthenticatedSampleLesson1RouteImport } from './routes/_authenticated/sample/lesson-1'
import { Route as AuthenticatedLessonFixtureRouteImport } from './routes/_authenticated/lesson/fixture'
import { Route as AuthenticatedJourneyNewRouteImport } from './routes/_authenticated/journey/new'
import { Route as AuthenticatedJourneyJourneyIdInterviewRouteImport } from './routes/_authenticated/journey/$journeyId/interview'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDemoStreamRoute = ApiDemoStreamRouteImport.update({
  id: '/api/demo-stream',
  path: '/api/demo-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSampleRoute = AuthenticatedSampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotaFixtureRoute =
  AuthenticatedQuotaFixtureRouteImport.update({
    id: '/quota-fixture',
    path: '/quota-fixture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSampleIndexRoute =
  AuthenticatedSampleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSampleQuizRoute = AuthenticatedSampleQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedSampleRoute,
} as any)
const AuthenticatedSampleLesson2Route =
  AuthenticatedSampleLesson2RouteImport.update({
    id: '/lesson-2',
    path: '/lesson-2',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const AuthenticatedSampleLesson1Route =
  AuthenticatedSampleLesson1RouteImport.update({
    id: '/lesson-1',
    path: '/lesson-1',
    getParentRoute: () => AuthenticatedSampleRoute,
  } as any)
const AuthenticatedLessonFixtureRoute =
  AuthenticatedLessonFixtureRouteImport.update({
    id: '/lesson/fixture',
    path: '/lesson/fixture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJourneyNewRoute = AuthenticatedJourneyNewRouteImport.update({
  id: '/journey/new',
  path: '/journey/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJourneyJourneyIdInterviewRoute =
  AuthenticatedJourneyJourneyIdInterviewRouteImport.update({
    id: '/journey/$journeyId/interview',
    path: '/journey/$journeyId/interview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/sample': typeof AuthenticatedSampleRouteWithChildren
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/journey/new': typeof AuthenticatedJourneyNewRoute
  '/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sample/': typeof AuthenticatedSampleIndexRoute
  '/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/': typeof AuthenticatedIndexRoute
  '/journey/new': typeof AuthenticatedJourneyNewRoute
  '/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sample': typeof AuthenticatedSampleIndexRoute
  '/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/quota-fixture': typeof AuthenticatedQuotaFixtureRoute
  '/_authenticated/sample': typeof AuthenticatedSampleRouteWithChildren
  '/api/demo-stream': typeof ApiDemoStreamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/journey/new': typeof AuthenticatedJourneyNewRoute
  '/_authenticated/lesson/fixture': typeof AuthenticatedLessonFixtureRoute
  '/_authenticated/sample/lesson-1': typeof AuthenticatedSampleLesson1Route
  '/_authenticated/sample/lesson-2': typeof AuthenticatedSampleLesson2Route
  '/_authenticated/sample/quiz': typeof AuthenticatedSampleQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/sample/': typeof AuthenticatedSampleIndexRoute
  '/_authenticated/journey/$journeyId/interview': typeof AuthenticatedJourneyJourneyIdInterviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/account'
    | '/quota-fixture'
    | '/sample'
    | '/api/demo-stream'
    | '/journey/new'
    | '/lesson/fixture'
    | '/sample/lesson-1'
    | '/sample/lesson-2'
    | '/sample/quiz'
    | '/api/auth/$'
    | '/sample/'
    | '/journey/$journeyId/interview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/sign-in'
    | '/account'
    | '/quota-fixture'
    | '/api/demo-stream'
    | '/'
    | '/journey/new'
    | '/lesson/fixture'
    | '/sample/lesson-1'
    | '/sample/lesson-2'
    | '/sample/quiz'
    | '/api/auth/$'
    | '/sample'
    | '/journey/$journeyId/interview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/sign-in'
    | '/_authenticated/account'
    | '/_authenticated/quota-fixture'
    | '/_authenticated/sample'
    | '/api/demo-stream'
    | '/_authenticated/'
    | '/_authenticated/journey/new'
    | '/_authenticated/lesson/fixture'
    | '/_authenticated/sample/lesson-1'
    | '/_authenticated/sample/lesson-2'
    | '/_authenticated/sample/quiz'
    | '/api/auth/$'
    | '/_authenticated/sample/'
    | '/_authenticated/journey/$journeyId/interview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  ApiDemoStreamRoute: typeof ApiDemoStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/demo-stream': {
      id: '/api/demo-stream'
      path: '/api/demo-stream'
      fullPath: '/api/demo-stream'
      preLoaderRoute: typeof ApiDemoStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sample': {
      id: '/_authenticated/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof AuthenticatedSampleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quota-fixture': {
      id: '/_authenticated/quota-fixture'
      path: '/quota-fixture'
      fullPath: '/quota-fixture'
      preLoaderRoute: typeof AuthenticatedQuotaFixtureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample/': {
      id: '/_authenticated/sample/'
      path: '/'
      fullPath: '/sample/'
      preLoaderRoute: typeof AuthenticatedSampleIndexRouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sample/quiz': {
      id: '/_authenticated/sample/quiz'
      path: '/quiz'
      fullPath: '/sample/quiz'
      preLoaderRoute: typeof AuthenticatedSampleQuizRouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/sample/lesson-2': {
      id: '/_authenticated/sample/lesson-2'
      path: '/lesson-2'
      fullPath: '/sample/lesson-2'
      preLoaderRoute: typeof AuthenticatedSampleLesson2RouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/sample/lesson-1': {
      id: '/_authenticated/sample/lesson-1'
      path: '/lesson-1'
      fullPath: '/sample/lesson-1'
      preLoaderRoute: typeof AuthenticatedSampleLesson1RouteImport
      parentRoute: typeof AuthenticatedSampleRoute
    }
    '/_authenticated/lesson/fixture': {
      id: '/_authenticated/lesson/fixture'
      path: '/lesson/fixture'
      fullPath: '/lesson/fixture'
      preLoaderRoute: typeof AuthenticatedLessonFixtureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journey/new': {
      id: '/_authenticated/journey/new'
      path: '/journey/new'
      fullPath: '/journey/new'
      preLoaderRoute: typeof AuthenticatedJourneyNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journey/$journeyId/interview': {
      id: '/_authenticated/journey/$journeyId/interview'
      path: '/journey/$journeyId/interview'
      fullPath: '/journey/$journeyId/interview'
      preLoaderRoute: typeof AuthenticatedJourneyJourneyIdInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSampleRouteChildren {
  AuthenticatedSampleLesson1Route: typeof AuthenticatedSampleLesson1Route
  AuthenticatedSampleLesson2Route: typeof AuthenticatedSampleLesson2Route
  AuthenticatedSampleQuizRoute: typeof AuthenticatedSampleQuizRoute
  AuthenticatedSampleIndexRoute: typeof AuthenticatedSampleIndexRoute
}

const AuthenticatedSampleRouteChildren: AuthenticatedSampleRouteChildren = {
  AuthenticatedSampleLesson1Route: AuthenticatedSampleLesson1Route,
  AuthenticatedSampleLesson2Route: AuthenticatedSampleLesson2Route,
  AuthenticatedSampleQuizRoute: AuthenticatedSampleQuizRoute,
  AuthenticatedSampleIndexRoute: AuthenticatedSampleIndexRoute,
}

const AuthenticatedSampleRouteWithChildren =
  AuthenticatedSampleRoute._addFileChildren(AuthenticatedSampleRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedQuotaFixtureRoute: typeof AuthenticatedQuotaFixtureRoute
  AuthenticatedSampleRoute: typeof AuthenticatedSampleRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedJourneyNewRoute: typeof AuthenticatedJourneyNewRoute
  AuthenticatedLessonFixtureRoute: typeof AuthenticatedLessonFixtureRoute
  AuthenticatedJourneyJourneyIdInterviewRoute: typeof AuthenticatedJourneyJourneyIdInterviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedQuotaFixtureRoute: AuthenticatedQuotaFixtureRoute,
  AuthenticatedSampleRoute: AuthenticatedSampleRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedJourneyNewRoute: AuthenticatedJourneyNewRoute,
  AuthenticatedLessonFixtureRoute: AuthenticatedLessonFixtureRoute,
  AuthenticatedJourneyJourneyIdInterviewRoute:
    AuthenticatedJourneyJourneyIdInterviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  ApiDemoStreamRoute: ApiDemoStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
